/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetailDto } from './order-detail-dto';
import { CustomerDto } from './customer-dto';


export interface OrderDto { 
    id?: number;
    details?: Array<OrderDetailDto>;
    customer?: CustomerDto;
    purchased?: string;
    paid?: number;
    sum?: number;
    difference?: number;
}

