/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductDto { 
    id?: number;
    uuid?: string;
    name?: string;
    description?: string;
    unit?: ProductDto.UnitEnum;
    price?: number;
}
export namespace ProductDto {
    export type UnitEnum = 'kilogramm' | 'liter' | 'flasche' | 'kiste';
    export const UnitEnum = {
        Kilogramm: 'kilogramm' as UnitEnum,
        Liter: 'liter' as UnitEnum,
        Flasche: 'flasche' as UnitEnum,
        Kiste: 'kiste' as UnitEnum
    };
}


